# Generated by Django 4.0.3 on 2023-12-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='role',
        ),
    ]
