# Generated by Django 4.0.3 on 2023-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr_App', '0002_remove_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr_admin', 'HR Admin')], default='employee', max_length=10),
        ),
    ]
