# Generated by Django 4.0.3 on 2023-12-27 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hr_App', '0003_employees_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_App.employees')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hr_App.leaves')),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='employeebenefits',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeequalification',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeequalification',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='reportdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='reportdepartment',
            name='report',
        ),
        migrations.AddField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='leadership',
            field=models.IntegerField(choices=[(1, 'Occasionally Demonstrated'), (2, 'Frequently Demonstrated'), (3, 'Consistently Demonstrated')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.CharField(max_length=255000),
        ),
        migrations.DeleteModel(
            name='Benefits',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='EmployeeBenefits',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeQualification',
        ),
        migrations.DeleteModel(
            name='Qualifications',
        ),
        migrations.DeleteModel(
            name='ReportDepartment',
        ),
    ]
